# Generated by Django 4.0 on 2024-05-23 11:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=225, verbose_name='Brand Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='./brand/image', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['JPEG', 'PNG', 'JPG'])], verbose_name='Brand Logo')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200, verbose_name='Category Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='./category/image', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['JPEG', 'JPG', 'PNG'])], verbose_name='Image')),
            ],
        ),
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popular', models.BooleanField(blank=True, default=False)),
                ('product_number', models.CharField(blank=True, help_text='generated automatically', max_length=100, null=True, verbose_name='Product Number')),
                ('product_name', models.CharField(max_length=500, verbose_name='Product Name')),
                ('price', models.FloatField(default=0, verbose_name='Price')),
                ('tax_rate', models.CharField(blank=True, choices=[('12', '12%'), ('18', '18%'), ('28', '28%')], max_length=5, null=True, verbose_name='Tax Rate')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('description', models.TextField(blank=True, max_length=10000, null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, max_length=1000, null=True, upload_to='./product/image', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['JPEG', 'PNG', 'JPG'])], verbose_name='Main Image')),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='accounts.userprofile', verbose_name='Added By')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='accounts.brand', verbose_name='Brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='accounts.productcategory', verbose_name='Category')),
            ],
        ),
    ]
